"""
TASK 3: Complete Agent Communication Workflow

Objective:
Demonstrate the full lifecycle of communicating with an Azure AI agent.
This is the most comprehensive task, covering all interactions you'll need
in a real application.

Learning Goals:
- Initiate conversations with agents (thread creation)
- Send messages and receive responses
- Process and extract response content
- Retrieve complete conversation history
- Handle file artifacts (charts, images, documents)

Workflow Overview:
1. START CONVERSATION - Create a thread (conversation container)
2. SEND MESSAGE - Send a user query to the agent
3. PROCESS RESPONSE - Extract text content and identify files
4. GET HISTORY - Retrieve all previous messages in the thread
5. HANDLE FILES - Download and save any artifacts from responses

Why This Matters:
Real applications need to:
- Maintain conversation continuity (threads)
- Handle diverse response types (text, files, structured data)
- Preserve interaction history for auditing and analysis
- Work with files and artifacts generated by agents
- Manage multi-turn conversations with context

Key Concepts:
- Thread: A conversation container that maintains context across messages
- Message: A single turn in the conversation (user or assistant)
- Response: The result of sending a message
- Artifact: Files, charts, or other outputs generated by the agent
"""

import os
import asyncio
from dotenv import load_dotenv
from azure_client import AzureAIFoundryClient, AzureAIConfig
from azure.identity import DefaultAzureCredential

# Load environment variables from .env file
load_dotenv()


def load_configuration():
    """
    Load and validate configuration from environment variables.
    
    Returns:
        tuple: (endpoint, agent_id, config, credential) or (None, None, None, None) if validation fails
    """
    endpoint = os.getenv("AZURE_AI_FOUNDRY_ENDPOINT")
    agent_id = os.getenv("AZURE_AI_AGENT_ID")
    
    if not endpoint:
        print("❌ AZURE_AI_FOUNDRY_ENDPOINT not found in environment variables")
        print("   Please copy .env.example to .env and fill in your endpoint")
        return None, None, None, None
    if not agent_id:
        print("❌ AZURE_AI_AGENT_ID not found in environment variables")
        print("   Please copy .env.example to .env and fill in your agent ID")
        print("   You can create an agent in Azure AI Foundry or use Task 2")
        return None, None, None, None
    
    print(f"Configuration loaded from .env:")
    print(f"  Endpoint: {endpoint}")
    print(f"  Agent ID: {agent_id}")
    print()
    
    config = AzureAIConfig(endpoint=endpoint, agent_id=agent_id)
    credential = DefaultAzureCredential()
    
    return endpoint, agent_id, config, credential


async def subtask_1_start_conversation(client):
    """
    SUB-TASK 1: Start a conversation thread with the agent.
    
    Args:
        client: AzureAIFoundryClient instance
        
    Returns:
        bool: True if conversation started successfully, False otherwise
    """
    print("=" * 60)
    print("SUB-TASK 1: Start Conversation")
    print("=" * 60)
    print("Creating a new conversation thread with the agent...")
    print()
    
    success = await client.start_conversation()
    if not success:
        print("❌ Failed to start conversation")
        print("   Verify your agent ID and credentials")
        return False
    
    print("✅ Conversation started successfully!")
    print(f"   Thread ID: {client.thread_id}")
    print("   This ID uniquely identifies your conversation")
    print()
    
    return True


async def subtask_2_send_message(client, message="What is the capital of France?"):
    """
    SUB-TASK 2: Send a message to the agent and receive a response.
    
    Args:
        client: AzureAIFoundryClient instance
        message: The message to send (default: "What is the capital of France?")
        
    Returns:
        object: Response object if successful, None otherwise
    """
    print("=" * 60)
    print("SUB-TASK 2: Send Message to Agent")
    print("=" * 60)
    
    # WORKSHOP TASK: Modify this message to test different queries
    print(f"Sending message: '{message}'")
    print()
    
    response = await client.send_message(message)
    
    if not response or response.error:
        print(f"❌ Failed to send message: {response.error if response else 'No response'}")
        print("   Possible causes:")
        print("   1. Agent is not running or not accessible")
        print("   2. Message format is incorrect")
        print("   3. Agent configuration is incomplete")
        return None
    
    print()
    return response


async def subtask_3_process_response(response):
    """
    SUB-TASK 3: Process and display the agent's response.
    
    Args:
        response: Response object from the agent
        
    Returns:
        bool: True if response processing succeeded
    """
    print("=" * 60)
    print("SUB-TASK 3: Process Agent Response")
    print("=" * 60)
    
    if response.message:
        print("✅ Agent Response (Text):")
        print(f"   {response.message}")
    else:
        print("   No text message in response")
    
    if response.charts:
        print(f"✅ Found {len(response.charts)} file(s) in response:")
        for chart in response.charts:
            print(f"   - {chart['filename']} (ID: {chart['file_id']})")
    else:
        print("   No files in response")
    print()
    
    return True


async def subtask_4_get_conversation_history(client):
    """
    SUB-TASK 4: Retrieve and display the complete conversation history.
    
    Args:
        client: AzureAIFoundryClient instance
        
    Returns:
        list: List of messages if successful, None otherwise
    """
    print("=" * 60)
    print("SUB-TASK 4: Retrieve Conversation History")
    print("=" * 60)
    
    print("Fetching complete conversation history...")
    print()
    
    history = await client.get_conversation_history()
    
    if history:
        print(f"✅ Conversation history ({len(history)} message(s)):")
        print()
        
        for i, msg in enumerate(history, 1):
            role_str = msg.role.value if hasattr(msg.role, 'value') else str(msg.role)
            print(f"  Message {i}: [{role_str}]")
            print(f"    Content: {msg.content}")
            
            if msg.timestamp:
                print(f"    Timestamp: {msg.timestamp}")
            print()
    else:
        print("⚠️ No conversation history found")
        print("   This might indicate an issue retrieving the history")
    
    return history


async def subtask_5_handle_file_content(client, response):
    """
    SUB-TASK 5: Download and save any files from the agent response.
    
    Args:
        client: AzureAIFoundryClient instance
        response: Response object that may contain file references
        
    Returns:
        bool: True if file handling succeeded or no files to process
    """
    print("=" * 60)
    print("SUB-TASK 5: Handle File Content")
    print("=" * 60)
    
    if response.charts:
        print(f"Processing {len(response.charts)} file(s)...")
        print()
        
        for chart in response.charts:
            print(f"File: {chart['filename']}")
            print(f"  File ID: {chart['file_id']}")
            print(f"  Type: {chart['type']}")
            
            file_content = await client.get_file_content(chart['file_id'])
            
            if file_content:
                file_size = len(file_content)
                print(f"  Status: Downloaded ({file_size} bytes)")
                
                output_path = f"output_{chart['filename']}"
                with open(output_path, "wb") as f:
                    f.write(file_content)
                print(f"  Saved to: {output_path}")
            else:
                print(f"  Status: Failed to download")
            print()
    else:
        print("✅ No files to process")
    
    print()
    return True


async def main():
    """
    Main driver function for Task 3: Complete Agent Communication Workflow.
    
    This function orchestrates all sub-tasks:
    1. Start Conversation - Create a thread
    2. Send Message - Send a query to the agent
    3. Process Response - Extract and display response
    4. Get Conversation History - Retrieve all messages
    5. Handle File Content - Download any files
    
    WORKSHOP INSTRUCTIONS:
    - Work through each sub-task one at a time
    - Instructor will guide you through each function
    - Comment out sub-tasks to focus on specific steps:
      # success = await subtask_1_start_conversation(client)
    """
    print()
    print("=" * 60)
    print("TASK 3: Complete Agent Communication Workflow")
    print("=" * 60)
    print()
    
    # Load configuration
    endpoint, agent_id, config, credential = load_configuration()
    if not config:
        return
    
    client = AzureAIFoundryClient(config, credential=credential)
    
    # SUB-TASK 1: Start Conversation
    success = await subtask_1_start_conversation(client)
    if not success:
        return
    
    # SUB-TASK 2: Send Message
    response = await subtask_2_send_message(client, "What is the capital of France?")
    if not response:
        return
    
    # SUB-TASK 3: Process Response
    await subtask_3_process_response(response)
    
    # SUB-TASK 4: Get Conversation History
    await subtask_4_get_conversation_history(client)
    
    # SUB-TASK 5: Handle File Content (optional)
    #await subtask_5_handle_file_content(client, response)
    
    # Task complete
    print("=" * 60)
    print("Task 3 Complete!")
    print("=" * 60)
    print()
    print("YOU HAVE NOW LEARNED:")
    print("1. ✅ How to start conversations (threads)")
    print("2. ✅ How to send messages to agents")
    print("3. ✅ How to process different response types")
    print("4. ✅ How to retrieve conversation history")
    print("5. ✅ How to download file artifacts")
    print()



if __name__ == "__main__":
    asyncio.run(main())
